
name: Deploy to WordPress.org
on:
  push:
    tags:
    - "*"
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: git config
        run: |
          git config --global --add safe.directory *
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: WordPress Plugin Deploy
        run: |
          git config --global --add safe.directory *
        uses: 10up/action-wordpress-plugin-deploy@master
        env:
          SVN_PASSWORD: ${{secrets.SVN_PASSWORD}}
          SVN_USERNAME: ${{secrets.SVN_USERNAME}}
          SLUG: login-with-phone-number
